services:
  nginx:
    container_name: proxy-nginx
    build: .
    ports:
      - "80:80"
  rust:
    container_name: proxy-auth-app
    build: ./Proxy_Authenticator_App/
  db:
    container_name: proxy-mysql-db
    image: mysql:lts
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: examplepassword
      MYSQL_DATABASE: Proxy_Authenticator_DB