services:
  nginx:
    container_name: proxy-nginx
    build: .
    ports:
      - "80:80"
  rust:
    container_name: proxy-auth-app
    build: ./Proxy_Authenticator_App/
    ports:
      - "8080:8080"
  db:
    container_name: proxy-mysql-db
    build: ./mySQL/
    ports:
      - "3307:3306"
