[package]
name = "Proxy_Authenticator_App"
version = "0.1.0"
edition = "2024"

[dependencies]
mysql = "25.0.0"
rpassword = "7"
webauthn-rs = "0.5"
tokio = { version = "1", features = ["full"] }
ngx = "0.5.0"


